### ISSUE TITLE
Should not activate on pages that have their own dark mode

### ISSUE THREAD

**Issue by benjamineskola** [unmade/Nightshift#2]
If I visit e.g. GitHub with system dark mode enabled and GitHub configured to obey the system preference, Nightshift will still activate and try to apply its own generated dark mode.

This conflicts with the "real" dark mode and seems to appear worse than Nightshift's generated dark mode on sites that do not have their own dark mode.

In fact, it probably should not activate on any page which has a dark background.

**Comment by unmade** [comment]
I'm not sure how trivial it would be to detect whether the page is dark enough to not enable a dark mode. Also, I don't think there is a way to check styles for dark mode.

Maybe the solution suggested in #1 makes more sense?

**Comment by matthieugouel** [comment]
I suppose you could have check like, converting the original background color in greyscale and if greyscale is superior than 128 then invert?
